ods pdf file='Libraries\Documents\GroupMeans.pdf';
data one;
set Nick.Two;
proc ttest;
class female;
var wage;
run;
proc ttest;
class union;
var wage;
run;
data Two;
Set Nick.Two;
if educ>12 then college=1;
else college=0;  
proc ttest;
class black;
var college;
ods pdf close;
run;
