data one;
set Work.Project;
CORRUPTION1=CORRUPTION*-1;
ER_DD2= ER_DD**2;
NRRENTS2=NRRENTS**2;
LER_DD=log(ER_DD);
ENERGYIMPORTS2=ENERGYIMPORTS**2;
LRENEWABLE=log(RENEWABLE);
EDUCATION2=EDUCATION**2;
LEDUCATION=log(EDUCATION);
CORRUPTION2=CORRUPTION1**2;
FDI2=FDI**2;
if Country = 'UnitedKingdom' then COUNTRY=1;
if Country = 'Austria' then COUNTRY=1;
if Country = 'CzechRepublic' then COUNTRY=1;
if Country = 'Denmark' then COUNTRY=1;
if Country = 'Finland' then COUNTRY=1;
if Country = 'France' then COUNTRY=1; 
if Country = 'Germany' then COUNTRY=1; 
if Country = 'Hungary' then COUNTRY=1; 
if Country = 'Ireland' then COUNTRY=1;
if Country = 'Norway' then COUNTRY=1; 
if Country = 'Portugal' then COUNTRY=1; 
if Country = 'Spain' then COUNTRY=1; 
if Country = 'Sweden' then COUNTRY=1; 
if Country = 'Switzerland' then COUNTRY=1;

if Country = 'Canada' then COUNTRY=2;
if Country = 'UnitedStates' then COUNTRY=2;

if Country = 'Australia' then COUNTRY=3;
if Country = 'Japan' then COUNTRY=3;

if COUNTRY=1 then EUROPEW=1; else EUROPEW=0;
if COUNTRY=2 then NAMERICA=1; else NAMERICA=0;
if COUNTRY=3 then ASIAPACIFIC=1; else ASIAPACIFIC=0;
run;

ods pdf;

proc means;

proc sort;
by ASIAPACIFIC; 
run;

Proc Corr;
var ER_DD	RENEWABLE	NRRENTS	FDI	ENERGYIMPORTS	EDUCATION	CORRUPTION1;
by ASIAPACIFIC; 
run;

proc sort;
by EUROPEW; 
run;

Proc Corr;
var ER_DD	RENEWABLE	NRRENTS	FDI	ENERGYIMPORTS	EDUCATION	CORRUPTION1;
by EUROPEW;
run;

proc sort;
by NAMERICA; 
run;

Proc Corr;
var ER_DD	RENEWABLE	NRRENTS	FDI	ENERGYIMPORTS	EDUCATION	CORRUPTION1;
by NAMERICA;
run;

Proc Reg;
model RENEWABLE = ER_DD NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1/white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1 CORRUPTION2/white vif;
plot RENEWABLE*CORRUPTION1;
plot RENEWABLE*ER_DD;
plot RENEWABLE*EDUCATION;
plot RENEWABLE*ENERGYIMPORTS;
plot RENEWABLE*FDI;
plot RENEWABLE*NRRENTS;
run;
*three ommission*;
Proc Reg;
model RENEWABLE = ER_DD NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1 EUROPEW NAMERICA/white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1 ASIAPACIFIC EUROPEW /white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1  ASIAPACIFIC NAMERICA /white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1/white vif;
run;
*two ommission*;
Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1 EUROPEW NAMERICA/white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1 ASIAPACIFIC EUROPEW /white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1  ASIAPACIFIC NAMERICA /white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS FDI ENERGYIMPORTS EDUCATION CORRUPTION1/white vif;
run;

*one ommission*;
Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1 EUROPEW NAMERICA/white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1 ASIAPACIFIC EUROPEW /white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1  ASIAPACIFIC NAMERICA /white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1 /white vif;
run;

*Full model*;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1 CORRUPTION2 EUROPEW NAMERICA/white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1 CORRUPTION2 ASIAPACIFIC EUROPEW /white vif;
run;

Proc Reg;
model RENEWABLE = ER_DD ER_DD2	NRRENTS NRRENTS2 FDI ENERGYIMPORTS EDUCATION CORRUPTION1 CORRUPTION2 ASIAPACIFIC NAMERICA /white vif;
run;

Proc Reg;
model ER_DD = ER_DD2 FDI NRRENTS CORRUPTION1 ENERGYIMPORTS EDUCATION RENEWABLE/ VIF;
run; 

Proc Reg;
model NRRENTS= NRRENTS2 CORRUPTION1 ER_DD FDI ENERGYIMPORTS EDUCATION RENEWABLE/ VIF;
run; 

Proc Reg;
model CORRUPTION1= CORRUPTION2 NRRENTS ER_DD FDI ENERGYIMPORTS EDUCATION RENEWABLE/ VIF;
run; 

ods pdf close;


