data one; 
set Nick.Corruption;
if region ='Asia' then DAsia=1;
else DAsia=0;
if region ='Latin_America' then DLAmerica=1;
else DLAmerica=0;
if region ='Middle_East' then DMEast=1;
else DMEast=0;
if region ='North_America' then DNAmerica=1;
else DNAmerica=0;
if region ='Africa' then DAfrica=1;
else DAfrica=0;
if region ='Europe' then DEurope=1;
else DEurope=0;
run;
ods pdf;
proc reg;
model corruptwb = pcgdp DEurope DAfrica DMEast DAsia DLAmerica;
run;
ods pdf close;
